"""Initial migration

Revision ID: 11e18968f51b
Revises: 2efca3e46e7f
Create Date: 2025-10-10 08:49:58.186311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e18968f51b'
down_revision = '2efca3e46e7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.Column('camera_id', sa.String(length=50), nullable=True),
    sa.Column('coordinates', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('OVERCROWDING', 'UNAUTHORIZED_ACCESS', 'LOITERING', 'VIOLENCE', name='alerttype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', name='alertstatus'), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=100), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.create_index('idx_alert_status', ['status'], unique=False)
        batch_op.create_index('idx_alert_timestamp', ['timestamp'], unique=False)

    op.create_table('occupancy_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('occupancy_history', schema=None) as batch_op:
        batch_op.create_index('idx_occupancy_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('idx_occupancy_zone_time', ['zone_id', 'timestamp'], unique=False)

    op.create_table('person_track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.String(length=50), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('total_duration', sa.Integer(), nullable=True),
    sa.Column('path_coordinates', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tanod')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tanod',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('zone', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('person_track')
    with op.batch_alter_table('occupancy_history', schema=None) as batch_op:
        batch_op.drop_index('idx_occupancy_zone_time')
        batch_op.drop_index('idx_occupancy_timestamp')

    op.drop_table('occupancy_history')
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_index('idx_alert_timestamp')
        batch_op.drop_index('idx_alert_status')

    op.drop_table('alert')
    op.drop_table('zone')
    # ### end Alembic commands ###
